### ISSUE TITLE
Feature: User can search up specific anime by name

### ISSUE THREAD

**Issue by khan-osama** [khan-osama/Kami#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search up specific anime by name in the search box on the home page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to type in the name of anime within the search box that is located on the home page. Then the user can click on the search button which will redirect them to a landing page with the search results or inform the user that no results were found.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![search](https://user-images.githubusercontent.com/63980419/167691462-97cf42e3-4a6a-41e2-bbbe-ba23773d17ae.png)
![homepage](https://user-images.githubusercontent.com/63980419/167691483-e54045e0-dbd5-433d-88eb-b89e094fa864.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to have a nav bar
- [x] Update nav component to route to appropriate pages
- [x] Create background image splash screeen
- [x] Import bootstrap search component
- [x] Create currently airing section with up to 5 airing anime
- [x] Create upcoming season section with up to 5 airing anime
- [x] Update app.jsx to fetch a GET request for currently airing anime
- [x] Render images for currently airing anime and titles
- [x] Update app.jsx to fetch a GET request for upcoming airing anime
- [x] Render images for upcoming airing anime and titles
- [x] If no search results are found, render a message for the user
- [x] Update background image splash screen to change on refresh with a random image

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
