### ISSUE TITLE
Feature: User can leave a review for anime

### ISSUE THREAD

**Issue by khan-osama** [khan-osama/Kami#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![related](https://user-images.githubusercontent.com/63980419/167692722-7c1a8248-6e76-452d-9f6d-1a858be160da.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to add a review table with userId and malId
- [x] Update `data.sql` to add some dummy review data

### ☁️ Server

- [x] Update `server/index.js` to add post and get request to store and retrieve reviews for each anime
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update details component page to have a review section
- [x] Review section should have a form where user can leave a review and submit
- [x] button should be disabled if the user is not logged in 
- [x] Reviews should show below the form and show who left the review
- [x] Clicking the submit button should trigger a fetch post request to the server/database
- [x] Loading the details page should trigger a get request to the server/database and store those reviews in an array
- [x] The array should be looped through and rendered out the reviews with the appropriate information

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
