### ISSUE TITLE
Feature: User can see details of an anime by clicking on it

### ISSUE THREAD

**Issue by khan-osama** [khan-osama/Kami#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![details](https://user-images.githubusercontent.com/63980419/167692267-2e531ad0-b0f1-44cc-8caa-39eb436d9700.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update anime that are being rendered to route path to specific anime title
- [x] Update route path to include anime title and details
- [x] Make all anime cursor pointers, image and titles
- [x] Render an empty details page
- [x] Create details page component
- [x] Render details page to match mockups
- [x] Call fetch request to grab specific anime data
- [x] Insert data into each appropriate element of the page
- [x] Data persists after refresh

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
