### ISSUE TITLE
Feature: User can see related anime for a specific anime within the details page

### ISSUE THREAD

**Issue by khan-osama** [khan-osama/Kami#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![related](https://user-images.githubusercontent.com/63980419/167692421-fe3e0f75-4ff6-4251-851f-a5c5b8410ff5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update Details component to show related shows section
- [x] Fetch request related shows title, relation and image for show
- [x] Make related show title clickable 
- [x] Render each show correctly with relations
- [x] Fetch new data for related show once user clicks on it 
- [x] Render new data and new related shows once user clicks on the related anime
- [x] Change animeId in route path to show that user clicks on

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
