### ISSUE TITLE
Feature: User can see an episode list of the anime

### ISSUE THREAD

**Issue by khan-osama** [khan-osama/Kami#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![related](https://user-images.githubusercontent.com/63980419/167692489-ae780aa7-dc84-4da7-84e5-234d93e24b1c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update Details component to fetch episode data based on mal_id
- [x] Store data in details component state
- [x] After fetching data, set up divs to place episodes in
- [x] Map over episodes in order to render p elements with episode information
- [x] Split episodes into 2 columns
- [x] Limit data to 50 episodes

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
