### ISSUE TITLE
Feature: User can save favorite anime

### ISSUE THREAD

**Issue by khan-osama** [khan-osama/Kami#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![save](https://user-images.githubusercontent.com/63980419/167692620-eba9379c-91d0-410b-a69f-c62551b27347.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a saved anime table with user id and saved anime
- [x] Update `data.sql` to have a dummy user with saved anime

### ☁️ Server

- [x] Update `server/index.js` to send a post request to the server whenever an anime is saved
- [x] Update the saved table to add the saved anime mal id, title and image url with the user who clicked it
- [x] Update `server/index.js` to send get request to server when user tries to access saved anime
- [x] Store saved anime in an array when retrieving
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update component in the details page to change to remove button once user clicks save
- [x] Make sure nothing happens when user is not logged in
- [x] Save mal id for anime that gets saved
- [x] Keep remove and save buttons consistent for every anime
- [x] Allow user to access saved anime on page
- [x] render correct anime for each user
- [x] If user is not logged in render no anime

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
